export const retreats = [
  {
    title: "4 Day Yoga live music, Snorkeling and Horseback Riding",
    highlights: [
      "Bilingual retreat",
      "Integral yoga classes daily",
      "Sound meditation sessions daily",
      "Horseback riding in the cenotes and caves",
      "Vegetarian/vegan breakfast and dinner",
      "Reef snorkeling excursion",
      "3 nights accommodation",
    ],
    link: 'https://www.bookyogaretreats.com/yoga-kundalini-teacher-training-in-cozumel/4-day-yoga-snorkeling-and-horseback-riding-retreat-in-cozumel',
    promo: true,
  },
  {
    title: "7 Day Yoga Dance and Astrology Retreat",
    highlights: [
      "Daily yoga practice",
      "The roots of Astrology, Yoga therapy and the 49 chakras",
      "Goups Dinamycs by elements, Tierra, Agua, Fuego, Aire, Ether",
      "Meditation and Kirtan (canto de mantras), sound healing, crystal bowls meditation",
      "Cacao ceremony static dance",
      "Sunrise yoga beach",
      "Vegetarian breakfast, lunch and dinner",
      "6 nights accommodation",
    ],
    link: 'https://www.tripaneer.com/yoga-kundalini-teacher-training-in-cozumel/14-days-yoga-therapy-and-pranachikitza-retreat-in-cozumel',
    promo: true,
  },
  {
    title: "4 Day Yoga Retreat with Massages and Mayan Canoe on the island of Cozumel",
    highlights: [
      "Mayan canoe tour",
      "Daily yoga classes",
      "1-hour massages sessions",
      "Suitable for all levels of practice",
      "English and/or Spanish instruction",
      "Vegetarian breakfast and dinner",
      "3 nights accommodation",
    ],
    link: 'https://www.tripaneer.com/yoga-kundalini-teacher-training-in-cozumel/4-day-yoga-retreat-with-massages-and-mayan-canoe-in-the-island-of-cozumel',
    promo: true,
  },
  {
    title: "7 Day Kundalini Tantra Yoga Retreat",
    highlights: [
      "Daily kundalini yoga practice and theory classes",
      "Group dynamics by Chakras and elements",
      "Ceremonies, sound healing sessions",
      "Crystal bowl meditation",
      "Cacao meditation",
      "Sunrise yoga class at the beach",
      "Canoa mayan sunset tour",
      "Manual to take into your teaching future",
      "3 home cooked vegetarian meals",
      "6 nights accommodation",
    ],
    link: 'https://www.bookyogaretreats.com/yoga-kundalini-teacher-training-in-cozumel/14-day-kundalini-tantra-yoga-retreat-in-cozumel',
    promo: false,
  },
]
